spring.application.name=nsu-capstone

spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:capstone_db}
spring.datasource.username=${POSTGRES_USER:capstone}
spring.datasource.password=${POSTGRES_PASSWORD:capstone1234}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
